on: [push]
name: deploy to aci

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/protohackers-server:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/protohackers-server:${{ github.sha }}
        - name: 'Deploy to Azure Container Instances'
          run: |
            az container create --resource-group protohackers --name protohackers-server --cpu 0.5 --memory 0.5 --image protohackers.azurecr.io/protohackers-server:${{ github.sha }} --ports 8080 --ports 8081 --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --ip-address public -o none